on:
    push:
        branches:
            - main

    workflow_dispatch:

name: Sync to dots

jobs:
    sync-files:
        strategy:
            matrix:
                file: [nvim, starship, lazygit, bat, fastfetch]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Sync ${{ matrix.file }}
              uses: scottmckendry/repo-files-clean-copy-sync@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
              with:
                  source_file: "${{ matrix.file }}/"
                  destination_repo: "scottmckendry/dots"
                  destination_folder: "/"
                  user_email: "39483124+scottmckendry@users.noreply.github.com"
                  user_name: "Scott McKendry"
                  commit_message: "${{ github.event.head_commit.message }}\n[skip ci]\nAutomated sync from scottmckendry/Windots"
                  git_server: "github.com"
